// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKv3kyB24b0yUL8FFMak4swxE43xTskvc',
    appId: '1:152257528049:web:fbd1a558b9a17679452950',
    messagingSenderId: '152257528049',
    projectId: 'galaxy-explorer-fa724',
    authDomain: 'galaxy-explorer-fa724.firebaseapp.com',
    storageBucket: 'galaxy-explorer-fa724.firebasestorage.app',
    measurementId: 'G-DGFE7TR73W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbJqS79E6pJQz7zuP6emAdam_dLweSvNM',
    appId: '1:152257528049:android:706d7d045f0f194b452950',
    messagingSenderId: '152257528049',
    projectId: 'galaxy-explorer-fa724',
    storageBucket: 'galaxy-explorer-fa724.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFEuwHQ9U1jkdd44WKP_XMwFjYKkQ51Z8',
    appId: '1:152257528049:ios:f0acd0b302cc2fe3452950',
    messagingSenderId: '152257528049',
    projectId: 'galaxy-explorer-fa724',
    storageBucket: 'galaxy-explorer-fa724.firebasestorage.app',
    iosBundleId: 'com.example.galaxyExplorer',
  );
}
